version: "3.8"
services: 
  backend:
    image: darshanusha2/stream-api
    volumes: 
      - data:/app
    ports: 
      - 3001:3000
  frontend:
    image: darshanusha2/stream-with-google-auth
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes: 
  data:
